services:
  proxy:
    build:
      context: gateway
    ports:
      - "127.0.0.1:8080:8080"
    profiles: [all]
    depends_on:
      - ccomp-backend

  ccomp-backend:
    build: .
    profiles: [all]
    env_file:
      - .env
    deploy:
      replicas: 2
    depends_on:
      grafana-lgtm:
        condition: service_started
      seaweeds:
        condition: service_healthy
      seaweeds-setup:
        condition: service_completed_successfully
      postgres-db:
        condition: service_healthy
    volumes:
      - ./keys:/app/keys

  postgres-db:
    image: postgres:17-alpine
    profiles: [ all, infra ]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  seaweeds:
    image: chrislusf/seaweedfs:latest
    profiles: [ all, infra ]
    environment:
      STORAGE_USER: ${STORAGE_USER}
      STORAGE_PASSWORD: ${STORAGE_PASSWORD}
    entrypoint: >
      sh -c "
      mkdir -p /etc/seaweedfs &&
      printf '{\"identities\":[{\"name\":\"%s\",\"credentials\":[{\"accessKey\":\"%s\",\"secretKey\":\"%s\"}],\"actions\":[\"Admin\",\"Read\",\"Write\"]}]}' \"$$STORAGE_USER\" \"$$STORAGE_USER\" \"$$STORAGE_PASSWORD\" > /etc/seaweedfs/s3.json &&
      weed server -s3 -s3.port=9000 -s3.config=/etc/seaweedfs/s3.json -dir=/data
      "
    volumes:
      - seaweed-data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9333/cluster/status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  seaweeds-setup:
    image: amazon/aws-cli
    profiles: [ all, infra ]
    depends_on:
      seaweeds:
        condition: service_healthy
    environment:
      AWS_ACCESS_KEY_ID: ${STORAGE_USER}
      AWS_SECRET_ACCESS_KEY: ${STORAGE_PASSWORD}
      AWS_DEFAULT_REGION: us-east-1
    entrypoint: /bin/sh
    command: >
      -c "
      until curl -s http://seaweeds:9000 > /dev/null; do echo 'Aguardando S3 API...'; sleep 2; done;
      aws --endpoint-url http://seaweeds:9000 s3 mb s3://images || true;
      aws --endpoint-url http://seaweeds:9000 s3api put-bucket-policy --bucket images --policy '{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":\"*\",\"Action\":\"s3:GetObject\",\"Resource\":\"arn:aws:s3:::images/*\"}]}';
      "

  rabbitmq:
    image: rabbitmq:4.3.5-management-alpine
    container_name: ccomp-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "127.0.0.1:15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    profiles: [ all, infra ]
    ports:
      - "127.0.0.1:3000:3000"

volumes:
  postgres-data:
  seaweed-data:
  rabbitmq_data: