services:
  proxy:
    build:
      context: gateway
    ports:
      - "8080:8080"
    profiles: [all]
    depends_on:
      - ccomp-backend

  ccomp-backend:
    build: .
    profiles: [all]
    env_file:
      - .env.dev
    depends_on:
      grafana-lgtm:
        condition: service_started
      minio:
        condition: service_healthy
      minio-setup:
        condition: service_completed_successfully
      postgres-db:
        condition: service_healthy
      keygen:
        condition: service_completed_successfully
    volumes:
      - ./keys:/app/keys

  postgres-db:
    image: postgres:17-alpine
    profiles: [all, infra]
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ccomp-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  postgres-db-test:
    image: postgres:17-alpine
    profiles: [ test ]
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ccomp-db-test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data

  minio:
    image: minio/minio
    profiles: [all, infra]
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio-setup:
    image: minio/mc
    profiles: [all, infra]
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb --ignore-existing myminio/images;
      /usr/bin/mc anonymous set public myminio/images;
      exit 0;
      "

  keygen:
    image: alpine/openssl
    profiles: [all, infra]
    volumes:
      - ./keys:/keys
    entrypoint: sh
    command: >
      -c "
      if [ ! -f /keys/private.key ]; then
        openssl genpkey -algorithm RSA -out /keys/private.key -pkeyopt rsa_keygen_bits:2048;
        openssl rsa -pubout -in /keys/private.key -out /keys/public.key;
        chmod 644 /keys/private.key /keys/public.key;
        echo 'Chaves de dev geradas em ./keys';
      else
        echo 'Chaves já existem, pulando geração.';
      fi"

  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    profiles: [all, infra]
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: false
    ports:
      - '3000:3000' # UI
      - '4317:4317'
      - '4318:4318'

volumes:
  postgres-data:
  minio-data:
