events {}

http {
    server {
        listen 8080;

        location /about {
            default_type application/json;
            return 200 '{"description":"proxy","version":"0.1"}';
        }
    }
}