springdotenv.filename=.env.dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.default_schema=public

swagger.security.enabloed=false
swagger.username=admin
swagger.password=admin

logging.level.com.ccomp.br=debug