spring.application.name=ccomp

spring.jackson.deserialization.accept-empty-string-as-null-object=true
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.threads.virtual.enabled=true

spring.output.ansi.enabled=ALWAYS

#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true
# Se você usa prefixos personalizados:
#springdoc.api-docs.path=/v3/api-docs

jwt.access.expiration=1800
jwt.refresh.expiration=86400
jwt.public.key=classpath:public.key
jwt.private.key=classpath:private.key