# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=validate

# Logging
logging.level.root=warn
logging.level.com.ccomp.br=info

# Frontend
app.frontend.password-reset-url=${FRONTEND_PASSWORD_RESET_URL}

# JWT
jwt.access.expiration=900

# Erros
spring.web.error.include-stacktrace=never
spring.web.error.include-message=never
spring.web.error.include-binding-errors=never

# Actuator
management.server.port=8081
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized

# Datasource
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5