spring.application.name=ccomp
spring.profiles.active=dev
#spring.config.import=optional:file:.env[.properties]

spring.jackson.deserialization.accept-empty-string-as-null-object=true
spring.jackson.property-naming-strategy=SNAKE_CASE

spring.threads.virtual.enabled=true
spring.task.execution.mode=FORCE

spring.output.ansi.enabled=ALWAYS

#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true
# Se você usa prefixos personalizados:
#springdoc.api-docs.path=/v3/api-docs

jwt.access.expiration=900
jwt.refresh.expiration=604800
jwt.public.key=classpath:public.key
jwt.private.key=classpath:private.key

# para email
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE}