-- -----------------------------------------------------
-- 1. Usuários e Autenticação
-- -----------------------------------------------------
create table tb_users (
    id uuid not null,
    "name" varchar(255) not null,
    email_address varchar(255) not null unique,
    "password" varchar(255) not null,
    status_account varchar(25) not null check (status_account in ('ACTIVE','DEACTIVATED','BLOCKED')),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);

create table tb_roles (
    id bigint generated by default as identity,
    user_id uuid not null unique,
    "role" varchar(25) not null check ("role" in ('ADMIN','STAFF','USER')),
    primary key (id),
    constraint fk_roles_user foreign key (user_id) references tb_users (id)
);

create table tb_password_reset_token (
    hash_id varchar(255) not null,
    user_id uuid not null,
    created_at timestamp(6) not null,
    expires_at timestamp(6) not null,
    primary key (hash_id)
);

create table tb_refresh_token (
    id bigint generated by default as identity,
    user_id uuid not null unique,
    token varchar(255) not null unique,
    expiry_date timestamp(6) with time zone not null,
    primary key (id)
);

-- -----------------------------------------------------
-- 2. Audit Log
-- -----------------------------------------------------
create table tb_audit_log (
    id bigint generated by default as identity,
    "timestamp" timestamp(6) not null,
    actor_id uuid,
    actor_type varchar(20) not null check (actor_type in ('USER','SYSTEM','INTEGRATION')),
    "action" varchar(25) not null check ("action" in ('USER_BLOCKED','USER_UNLOCKED','USER_CHANGE_ROLE')),
    target_type varchar(30) not null check (target_type in ('USER','NEWS','CLUB','EVENT','ACTIVITY')),
    target_id varchar(255) not null,
    reason text,
    changes jsonb,
    primary key (id)
);

create index idx_audit_log_actor_id on tb_audit_log (actor_id);
create index idx_audit_log_target_id on tb_audit_log (target_id);
create index idx_audit_log_timestamp on tb_audit_log ("timestamp");

-- -----------------------------------------------------
-- 3. Clubes
-- -----------------------------------------------------
create table tb_clubs (
    id bigint generated by default as identity,
    "name" varchar(255) not null,
    summary varchar(255),
    content text,
    cover_image_url varchar(255),
    created_at timestamp(6),
    updated_at timestamp(6),
    published_at timestamp(6),
    primary key (id)
);

create table tb_club_members (
    id bigint generated by default as identity,
    club_id bigint not null,
    user_id uuid not null,
    "role" varchar(25) not null check ("role" in ('INSTRUCTOR','MEMBER')),
    status varchar(25) not null check (status in ('ACTIVE','CANCELLED','INACTIVE')),
    joined_at timestamp(6) not null,
    left_at timestamp(6),
    primary key (id),
    constraint uk_club_members_club_user unique (club_id, user_id),
    constraint fk_club_members_club foreign key (club_id) references tb_clubs (id)
);

create index idx_club_members_user_id on tb_club_members (user_id);
create index idx_club_members_club_id on tb_club_members (club_id);

-- -----------------------------------------------------
-- 4. Eventos e Atividades
-- -----------------------------------------------------
create table tb_events (
    id bigint generated by default as identity,
    title varchar(255) not null,
    slug varchar(255) not null unique,
    owner_id uuid not null,
    category varchar(25) not null check (category in ('ACADEMIC_EDUCATIONAL','CULTURE_ENTERTAINMENT','CORPORATE_BUSINESS','SOCIAL_POPULAR','SPORTS_WELLNESS','FOOD_DRINK','OTHER')),
    format varchar(20) not null check (format in ('IN_PERSON','HYBRID','ONLINE')),
    status varchar(20) not null check (status in ('DRAFT','PUBLISHED','UNLISTED','CANCELED')),
    summary text,
    content text,
    address varchar(255),
    online_url varchar(255),
    cover_image_url varchar(255),
    latitude float,
    longitude float,
    max_capacity integer,
    enrollment_paused boolean not null,
    start_date timestamp(6),
    end_date timestamp(6),
    enrollment_start_date timestamp(6),
    enrollment_end_date timestamp(6),
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create index idx_events_category on tb_events (category);
create index idx_events_format on tb_events (format);
create index idx_events_status on tb_events (status);
create index idx_events_start_date on tb_events (start_date);
create index idx_events_location on tb_events (latitude, longitude);

create table tb_event_activities (
    id bigint generated by default as identity,
    event_id bigint not null,
    title varchar(255) not null,
    description text,
    display_order bigint not null,
    created_at timestamp(6) not null,
    primary key (id),
    constraint fk_event_activities_event foreign key (event_id) references tb_events (id)
);

create table tb_event_editors (
    id bigint generated by default as identity,
    event_id bigint not null,
    user_id uuid not null,
    status varchar(20) not null check (status in ('ACTIVE','PENDING','REVOKED')),
    assigned_at timestamp(6) not null,
    revoked_at timestamp(6),
    primary key (id),
    constraint uk_tb_event_editors_event_user unique (event_id, user_id),
    constraint fk_event_editors_event foreign key (event_id) references tb_events (id)
);

create table tb_event_editor_validations (
    id bigint generated by default as identity,
    event_editor_id bigint not null,
    code uuid not null unique,
    expires_at timestamp(6) not null,
    primary key (id),
    constraint fk_event_editor_validations_editor foreign key (event_editor_id) references tb_event_editors (id) on delete cascade
);

create table tb_event_enrollments (
    id bigint generated by default as identity,
    events_id bigint not null,
    user_id uuid not null,
    status varchar(20) not null check (status in ('CONFIRMED','CHECKED_IN','CANCELED')),
    check_in_at timestamp(6),
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    primary key (id),
    constraint uk_event_user unique (events_id, user_id),
    constraint fk_event_enrollments_event foreign key (events_id) references tb_events (id)
);

create index idx_enrollment_user on tb_event_enrollments (user_id);
create index idx_enrollment_event_status on tb_event_enrollments (events_id, status);

-- -----------------------------------------------------
-- 5. Notícias
-- -----------------------------------------------------
create table tb_news (
    id bigint generated by default as identity,
    title varchar(255) not null,
    slug varchar(255) not null unique,
    author_id uuid not null,
    featured boolean not null,
    summary varchar(255),
    content text,
    cover_image_url varchar(255),
    blocks jsonb,
    created_at timestamp(6),
    updated_at timestamp(6),
    published_at timestamp(6),
    primary key (id)
);

create index idx_slug on tb_news (slug);

create table tb_news_editors (
    id bigint generated by default as identity,
    news_id bigint not null,
    user_id uuid not null,
    primary key (id),
    constraint uk_news_editors_userid_newsid unique (user_id, news_id)
);