-- Permite inscrições em atividades sem o usuário estar inscrito no evento.
-- Adiciona a relação N:M entre inscrições e atividades

ALTER TABLE tb_event_enrollments
	ALTER COLUMN events_id DROP NOT NULL;

CREATE TABLE tb_event_enrollment_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    enrollment_id BIGINT NOT NULL,
    activity_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,

    CONSTRAINT pk_event_enrollment_activities
        PRIMARY KEY (id),

    CONSTRAINT fk_enrollment_activity_enrollment
        FOREIGN KEY (enrollment_id)
        REFERENCES tb_event_enrollments (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_enrollment_activity_activity
        FOREIGN KEY (activity_id)
        REFERENCES tb_event_activities (id)
        ON DELETE CASCADE,

    CONSTRAINT uk_enrollment_activity
        UNIQUE (enrollment_id, activity_id)
);

CREATE INDEX idx_enrollment_activity_enrollment
    ON tb_event_enrollment_activities (enrollment_id);

CREATE INDEX idx_enrollment_activity_activity
    ON tb_event_enrollment_activities (activity_id);

CREATE INDEX idx_enrollment_activity_created_at
    ON tb_event_enrollment_activities (created_at);



